### ISSUE TITLE
Missing information in Keepers in Iron

### ISSUE THREAD

**Issue by icorreafalconi** [Vagabottos/root#48]
Many factions specify that in the Birdsong, Daylight and Evening phases the player must follow the steps in a particular order (or in any order, if the faction so requires). This is missing from the Keepers in Iron sections:

1. Your Birdsong has three steps in the following order.
2. Your Daylight has two steps in the following order. 
3. Your Evening has three steps in the following order.

**Comment by seiyria** [comment]
thanks!
